import { urlName, NAVS } from './navs';

export const SIDENAVS: urlName[] = [
  NAVS["pendahuluan"],
  NAVS["apa-itu-kubernetes"],
  NAVS["menyiapkan-kubernetes"],
  NAVS["memasang-kubernetes"],
  NAVS["membuat-cluster"],
  NAVS["menggunakan-berkas-config-kubernetes"],
  NAVS["mendaftarkan-private-docker-registry"],
  NAVS["menghapus-node-dari-cluster"],
  NAVS["memasang-lens-tidak-wajib"],
  NAVS["dasar-kubernetes"],
  NAVS["node"],
  NAVS["namespace"],
  NAVS["pod"],
  NAVS["pods-controller"],
  NAVS["deployment"],
  NAVS["daemonset"],
  NAVS["service"],
  NAVS["configuration"],
  NAVS["configmap"],
  NAVS["secret"],
  NAVS["resourcequota"],
  NAVS["limitrange"],
  NAVS["storage"],
  NAVS["volume"],
  NAVS["persistentvolume--persistentvolumeclaim"],
  NAVS["storageclass"],
  NAVS["pods-controller-ii"],
  NAVS["job"],
  NAVS["cronjob"],
  NAVS["statefulset"],
  NAVS["access-control"],
  NAVS["serviceaccount"],
  NAVS["role--rolebinding"]
]